// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: tools/protos/product.proto

package impl

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CategoryType int32

const (
	CategoryType_Unspecified      CategoryType = 0
	CategoryType_Consumable       CategoryType = 1
	CategoryType_Electrodomestics CategoryType = 2
	CategoryType_Utilitaries      CategoryType = 3
)

// Enum value maps for CategoryType.
var (
	CategoryType_name = map[int32]string{
		0: "Unspecified",
		1: "Consumable",
		2: "Electrodomestics",
		3: "Utilitaries",
	}
	CategoryType_value = map[string]int32{
		"Unspecified":      0,
		"Consumable":       1,
		"Electrodomestics": 2,
		"Utilitaries":      3,
	}
)

func (x CategoryType) Enum() *CategoryType {
	p := new(CategoryType)
	*p = x
	return p
}

func (x CategoryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CategoryType) Descriptor() protoreflect.EnumDescriptor {
	return file_tools_protos_product_proto_enumTypes[0].Descriptor()
}

func (CategoryType) Type() protoreflect.EnumType {
	return &file_tools_protos_product_proto_enumTypes[0]
}

func (x CategoryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CategoryType.Descriptor instead.
func (CategoryType) EnumDescriptor() ([]byte, []int) {
	return file_tools_protos_product_proto_rawDescGZIP(), []int{0}
}

type ProductList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductList []*Product `protobuf:"bytes,1,rep,name=ProductList,proto3" json:"ProductList,omitempty"`
}

func (x *ProductList) Reset() {
	*x = ProductList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tools_protos_product_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductList) ProtoMessage() {}

func (x *ProductList) ProtoReflect() protoreflect.Message {
	mi := &file_tools_protos_product_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductList.ProtoReflect.Descriptor instead.
func (*ProductList) Descriptor() ([]byte, []int) {
	return file_tools_protos_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductList) GetProductList() []*Product {
	if x != nil {
		return x.ProductList
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string        `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name  string        `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Specs *ProductSpecs `protobuf:"bytes,3,opt,name=Specs,proto3" json:"Specs,omitempty"`
}

func (x *Product) Reset() {
	*x = Product{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tools_protos_product_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_tools_protos_product_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_tools_protos_product_proto_rawDescGZIP(), []int{1}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetSpecs() *ProductSpecs {
	if x != nil {
		return x.Specs
	}
	return nil
}

type ProductSpecs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model        string               `protobuf:"bytes,1,opt,name=Model,proto3" json:"Model,omitempty"`
	CategoryType CategoryType         `protobuf:"varint,2,opt,name=CategoryType,proto3,enum=CategoryType" json:"CategoryType,omitempty"`
	LaunchDate   *timestamp.Timestamp `protobuf:"bytes,3,opt,name=LaunchDate,proto3" json:"LaunchDate,omitempty"`
}

func (x *ProductSpecs) Reset() {
	*x = ProductSpecs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tools_protos_product_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductSpecs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSpecs) ProtoMessage() {}

func (x *ProductSpecs) ProtoReflect() protoreflect.Message {
	mi := &file_tools_protos_product_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSpecs.ProtoReflect.Descriptor instead.
func (*ProductSpecs) Descriptor() ([]byte, []int) {
	return file_tools_protos_product_proto_rawDescGZIP(), []int{2}
}

func (x *ProductSpecs) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ProductSpecs) GetCategoryType() CategoryType {
	if x != nil {
		return x.CategoryType
	}
	return CategoryType_Unspecified
}

func (x *ProductSpecs) GetLaunchDate() *timestamp.Timestamp {
	if x != nil {
		return x.LaunchDate
	}
	return nil
}

type CategoryTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryType int32 `protobuf:"varint,1,opt,name=CategoryType,proto3" json:"CategoryType,omitempty"`
}

func (x *CategoryTypeRequest) Reset() {
	*x = CategoryTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tools_protos_product_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryTypeRequest) ProtoMessage() {}

func (x *CategoryTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tools_protos_product_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryTypeRequest.ProtoReflect.Descriptor instead.
func (*CategoryTypeRequest) Descriptor() ([]byte, []int) {
	return file_tools_protos_product_proto_rawDescGZIP(), []int{3}
}

func (x *CategoryTypeRequest) GetCategoryType() int32 {
	if x != nil {
		return x.CategoryType
	}
	return 0
}

var File_tools_protos_product_proto protoreflect.FileDescriptor

var file_tools_protos_product_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a,
	0x0b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x0b,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x0b, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x52, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x53, 0x70, 0x65, 0x63, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x53, 0x70, 0x65, 0x63, 0x73, 0x52, 0x05, 0x53, 0x70, 0x65, 0x63, 0x73, 0x22, 0x93, 0x01, 0x0a,
	0x0c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x70, 0x65, 0x63, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x31, 0x0a, 0x0c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68,
	0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x44, 0x61,
	0x74, 0x65, 0x22, 0x39, 0x0a, 0x13, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x2a, 0x56, 0x0a,
	0x0c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a,
	0x0b, 0x55, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x61, 0x62, 0x6c, 0x65, 0x10, 0x01, 0x12, 0x14,
	0x0a, 0x10, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x72, 0x6f, 0x64, 0x6f, 0x6d, 0x65, 0x73, 0x74, 0x69,
	0x63, 0x73, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x74, 0x69, 0x6c, 0x69, 0x74, 0x61, 0x72,
	0x69, 0x65, 0x73, 0x10, 0x03, 0x32, 0x4e, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x16, 0x6c, 0x69, 0x73, 0x74, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x14, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x26, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x5a, 0x1b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x6d, 0x70, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tools_protos_product_proto_rawDescOnce sync.Once
	file_tools_protos_product_proto_rawDescData = file_tools_protos_product_proto_rawDesc
)

func file_tools_protos_product_proto_rawDescGZIP() []byte {
	file_tools_protos_product_proto_rawDescOnce.Do(func() {
		file_tools_protos_product_proto_rawDescData = protoimpl.X.CompressGZIP(file_tools_protos_product_proto_rawDescData)
	})
	return file_tools_protos_product_proto_rawDescData
}

var file_tools_protos_product_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tools_protos_product_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tools_protos_product_proto_goTypes = []interface{}{
	(CategoryType)(0),           // 0: CategoryType
	(*ProductList)(nil),         // 1: ProductList
	(*Product)(nil),             // 2: Product
	(*ProductSpecs)(nil),        // 3: ProductSpecs
	(*CategoryTypeRequest)(nil), // 4: CategoryTypeRequest
	(*timestamp.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_tools_protos_product_proto_depIdxs = []int32{
	2, // 0: ProductList.ProductList:type_name -> Product
	3, // 1: Product.Specs:type_name -> ProductSpecs
	0, // 2: ProductSpecs.CategoryType:type_name -> CategoryType
	5, // 3: ProductSpecs.LaunchDate:type_name -> google.protobuf.Timestamp
	4, // 4: ProductService.listProductsByCategory:input_type -> CategoryTypeRequest
	1, // 5: ProductService.listProductsByCategory:output_type -> ProductList
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tools_protos_product_proto_init() }
func file_tools_protos_product_proto_init() {
	if File_tools_protos_product_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tools_protos_product_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tools_protos_product_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Product); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tools_protos_product_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductSpecs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tools_protos_product_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoryTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tools_protos_product_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tools_protos_product_proto_goTypes,
		DependencyIndexes: file_tools_protos_product_proto_depIdxs,
		EnumInfos:         file_tools_protos_product_proto_enumTypes,
		MessageInfos:      file_tools_protos_product_proto_msgTypes,
	}.Build()
	File_tools_protos_product_proto = out.File
	file_tools_protos_product_proto_rawDesc = nil
	file_tools_protos_product_proto_goTypes = nil
	file_tools_protos_product_proto_depIdxs = nil
}
